name: Deploy Smart Contract

on:
  workflow_dispatch:  # <-- Allows manual trigger from GitHub Actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables
      run: |
        echo "MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }}" >> $GITHUB_ENV
        echo "SEPOLIA_RPC_URL=${{ secrets.SEPOLIA_RPC_URL }}" >> $GITHUB_ENV
        echo "GOERLI_RPC_URL=${{ secrets.GOERLI_RPC_URL }}" >> $GITHUB_ENV
        echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> $GITHUB_ENV
        echo "ETHERSCAN_API_KEY=${{ secrets.ETHERSCAN_API_KEY }}" >> $GITHUB_ENV

    - name: Compile Contracts
      run: npx hardhat compile

    - name: Deploy Contracts to Sepolia
      run: npx hardhat run scripts/deploy.js --network sepolia
